BTN_1 = 'BTN_1'
BTN_2 = 'BTN_2'
BTN_3 = 'BTN_3'

BUTTON_BACK_IN_PLACE = 'IN_PLACE_BACK'

SECRET_LEVEL_BUTTON = 'SCRT_LVL'
CONFIRM_DECLINE_BROADCAST = 'CNFM_DCLN_BRDCST'
CONFIRM_BROADCAST = 'CONFIRM'
DECLINE_BROADCAST = 'DECLINE'