welcome = "Добро пожаловать!"
btn1 = "Кнопка №1"
btn2 = "Кнопка №2"
btn3 = "Кнопка №3"
pressed = "Вы нажали кнопку #"

go_back = "Вернуться"
confirm_broadcast = "Подтвердить"
decline_broadcast = "Отклонить"
secret_level = "Секретный уровень"
msg_sent = "Сообщение отослано"
share_location = "Позвольте мне узнать, откуда вы?"
thanks_for_location = "Спасибо за ваше местоположение!"
broadcast_command = '/broadcast'
broadcast_no_access = "Sorry, you don't have access to this function."
broadcast_header = "This message will be sent to all users.\n\n"
declined_message_broadcasting = "Рассылка сообщений отклонена❌\n\n"
error_with_markdown = "Невозможно обработать ваш текст в формате Markdown."
specify_word_with_error = " У вас ошибка в слове "
secret_admin_commands = "⚠️ Секретные команды администратора\n" \
                        "/stats - bot stats"
